BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE order_audit_log';
  EXECUTE IMMEDIATE 'DROP TABLE payments';
  EXECUTE IMMEDIATE 'DROP TABLE order_items';
  EXECUTE IMMEDIATE 'DROP TABLE orders';
  EXECUTE IMMEDIATE 'DROP TABLE products';
  EXECUTE IMMEDIATE 'DROP TABLE customers';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- CUSTOMERS
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(50),
  email VARCHAR2(50),
  phone VARCHAR2(15),
  city VARCHAR2(30)
);

-- PRODUCTS
CREATE TABLE products (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name VARCHAR2(50),
  category VARCHAR2(30),
  unit_price NUMBER(10,2),
  stock_qty NUMBER(10)
);

-- ORDERS
CREATE TABLE orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER,
  order_date DATE DEFAULT SYSDATE,
  order_status VARCHAR2(20),
  payment_status VARCHAR2(20),
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- ORDER_ITEMS
CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER,
  product_id NUMBER,
  quantity NUMBER,
  unit_price NUMBER(10,2),
  subtotal NUMBER(10,2),
  FOREIGN KEY (order_id) REFERENCES orders(order_id),
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- PAYMENTS
CREATE TABLE payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER,
  amount NUMBER(10,2),
  payment_mode VARCHAR2(20),
  payment_date DATE DEFAULT SYSDATE,
  FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- ORDER_AUDIT_LOG
CREATE TABLE order_audit_log (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER,
  old_status VARCHAR2(20),
  new_status VARCHAR2(20),
  changed_by VARCHAR2(50),
  changed_on DATE DEFAULT SYSDATE,
  remarks VARCHAR2(100),
  FOREIGN KEY (order_id) REFERENCES orders(order_id)
);
/
